### ISSUE TITLE
Important change in NSRR version need to correct tutorial SHHS tutorial Browsing SHHS documentation

### ISSUE THREAD

**Issue by JLArnold** [nsrr/shhs-documentation#10]
https://www.sleepdata.org/datasets/shhs/pages/tutorials/browsing-documentation.md

Important notice that the NSRR version changed, now there needs to be correction to the SHHS tutorial Browsing SHHS documentation, the screen shots showing searching for variables no long look like that and the two hyperlinks to "Variables" page and the example variable "Medications" no longer work and show error message.

![image](https://cloud.githubusercontent.com/assets/16805718/12621206/7fa87e4c-c4ed-11e5-92c9-8f4dc79ba638.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12621220/8da03382-c4ed-11e5-93bb-183caeb7fe34.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12621248/b7ae3e8a-c4ed-11e5-8325-02f2eb1a292b.png)

**Comment by remomueller** [comment]
These tutorials will be removed as they're pretty outdated.
