### ISSUE TITLE
Question symbol for respi events associated with desat or arousal ">" vs "≥" SHHS mop 6.6 Scoring Procedures 6.6.1 Overview of Scoring, RDI summary

### ISSUE THREAD

**Issue by JLArnold** [nsrr/shhs-documentation#44]
https://www.sleepdata.org/datasets/shhs/pages/mop/6-610-mop-overview-of-scoring.md

Question symbol for events associated with desat or arousal “>” vs “≥” SHHS mop 6.6 Scoring Procedures, 6.6.1 Overview of Scoring, RDI, Summary RDI with desats has “≥” by each desat level, the next line has just “>” for the desat levels or arousal. I would assume  that the same desat levels would be the same with or without arousal so that the symbol should be “≥” vs “>”
The same issue for page in CFS manual PSG Reading Center, Overview of Scoring, RDI summary.

Check with Mike R, but I think the best correction would be to make the two points look the same for the desat levels with “≥” in front of each desat value for events associated with desat or arousal.  Below is screen shot of page from the Long report with the values that go in the SAS report and the correct symbol is ">=" or "≥".

"•Summary RDI values based on events associated with > 2%,  3%, 4%, and  5% desaturation levels or associated arousal." Could be "•Summary RDI values based on events associated with ≥ 2%, ≥ 3%, ≥ 4%, and ≥ 5% desaturation levels or associated arousal."

![image](https://cloud.githubusercontent.com/assets/16805718/12798274/78ff0dc8-ca96-11e5-860c-f7ad282ef5ef.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12828454/f445075a-cb52-11e5-9b90-9c23dd21ca00.png)

**Comment by michellereid** [comment]
@mrueschman should the symbol be changed to ≥ ?

**Comment by mrueschman** [comment]
@michellereid I agree with changing to ≥
